### ISSUE TITLE
EmptyNotes helper class NOT found in the repository.

### ISSUE THREAD

**Issue by ashishkharcheiu** [prakashshuklahub/Simple-Note-App-with-Online-Storage#2]
EmptyNotes class is used in MainActivity.kt but is not available and displays error.

import com.languagexx.simplenotes.helper.EmptyNotes
--
25 | import com.languagexx.simplenotes.viewmodel.ViewModel
… |  
202 | val tag = data?.getStringExtra("tag")
203 | val color = data?.getStringExtra("color")
204 |  
205 | val empty = EmptyNotes.checkForEmptyNotes(title, description, tag, this)

**Comment by prakashshuklahub** [comment]
The helper package is removed , working code with mvvm is implemented.
